In [6]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [1]:
import numpy as np
import pandas as pd

In [2]:
array1 = np.random.rand(3, 2)
array2 = np.random.rand(2, 3)
print(array1)
print(array2)

[[0.08223636 0.05119363]
 [0.07993986 0.42465063]
 [0.5732374  0.37152218]]
[[0.98331106 0.35698749 0.0372601 ]
 [0.34163183 0.85270123 0.87321352]]


In [3]:
mul = np.dot(array1, array2)
print(mul)

[[0.0983533  0.07301023 0.04776711]
 [0.22367991 0.39063764 0.37378924]
 [0.69059448 0.521436   0.34577708]]


In [4]:
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res) 

[[0.09835330122666192, 0.07301022726496462, 0.04776710828882118], [0.22367991395274983, 0.39063764085213243, 0.37378923980752615], [0.6905944759774237, 0.5214360003562968, 0.34577707772347255]]


In [5]:
mean = np.mean(array1)
print(mean)

0.26379667678830915


In [7]:
main_data = pd.read_csv("/content/drive/MyDrive/mtcars.csv")

In [8]:
del main_data['model']
# Mean Centered
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())


        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
