In [2]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [3]:
import numpy as np
import pandas as pd

In [6]:
array1 = np.array([[4, 7, 3],[2, 8, 5]])
array2 = np.array([[-3,5],[-6, 4],[7, -9]])
print(array1)
print(array2)

[[4 7 3]
 [2 8 5]]
[[-3  5]
 [-6  4]
 [ 7 -9]]


In [7]:
array = np.random.rand(3, 4)
print(array)

[[0.35003257 0.76994672 0.03640438 0.90139522]
 [0.09685504 0.45005184 0.5952791  0.92670329]
 [0.9412234  0.42158291 0.08957186 0.11003249]]


In [8]:
mul = np.dot(array1, array2)
print(mul)

[[-33  21]
 [-19  -3]]


In [9]:
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res) 

[[-33, 21], [-19, -3]]


In [10]:
mean = np.mean(array1)
print(mean)

4.833333333333333


In [12]:
main_data = pd.read_csv("/content/drive/MyDrive/mtcars.csv")

In [13]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())


        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
