In [1]:
import numpy as np

Training

In [2]:
# temperature, rainfall and humidity
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [3]:
# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print(weights)
print(biases)

[[0.70425069 0.95574458 0.53495608]
 [0.70651423 0.94048153 0.29136277]]
[[0.93719293 0.53046385]
 [0.26522606 0.818419  ]
 [0.5310264  0.33206303]
 [0.31215204 0.76129792]
 [0.39172015 0.33258291]
 [0.72489714 0.0705774 ]
 [0.8996411  0.25393916]
 [0.78748562 0.97742498]
 [0.43047442 0.7093396 ]
 [0.03756617 0.23342892]
 [0.9883835  0.46178469]
 [0.04486049 0.6618089 ]
 [0.04808721 0.49662377]
 [0.91397619 0.78251488]
 [0.60678705 0.72950763]]


In [4]:
# Defining the model
def model(x):
    return x @ np.transpose(weights) + biases

# Generate predictions
preds = model(inputs)

# Compare with targets
print("Predictions : ", preds)
print("Targets : ",targets)

Predictions :  [[139.38549136 127.64686429]
 [182.69475073 166.52080594]
 [220.89806238 204.72236689]
 [133.03611405 124.0468775 ]
 [178.18342281 159.76368578]
 [139.17319557 127.18697784]
 [183.32916577 165.9563261 ]
 [221.1545216  205.36772884]
 [133.15443644 123.99491918]
 [177.82926883 159.66453178]
 [139.43668192 127.57818513]
 [182.47438515 166.36419584]
 [220.41512319 204.88692763]
 [133.63793821 124.06809446]
 [178.39848971 160.1606105 ]]
Targets :  [[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [6]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

# Compute loss
loss = mse(preds, targets)
print(loss)



13540.589035113831


In [7]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print(weights_grad)
print(biases_grad)

[[16297.2767012  16074.70819212 10153.23412766]
 [11238.59705228 10763.04221646  6762.20179306]]
[[11.11806551  7.68624857]
 [13.5593001   8.73610746]
 [13.58640832  9.56298225]
 [14.80481521 11.60625033]
 [10.02445637  5.4351581 ]
 [11.08975941  7.62493038]
 [13.64388877  8.66084348]
 [13.62060288  9.64903051]
 [14.82059153 11.59932256]
 [ 9.97723584  5.42193757]
 [11.12489092  7.67709135]
 [13.52991802  8.71522611]
 [13.52201642  9.58492368]
 [14.88505843 11.60907926]
 [10.05313196  5.4880814 ]]


In [8]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5
print(weights)
print(biases)

[[0.54127792 0.7949975  0.43342374]
 [0.59412826 0.83285111 0.22374076]]
[[0.93708175 0.53038699]
 [0.26509047 0.81833164]
 [0.53089054 0.3319674 ]
 [0.31200399 0.76118186]
 [0.39161991 0.33252856]
 [0.72478624 0.07050115]
 [0.89950467 0.25385255]
 [0.78734941 0.97732849]
 [0.43032622 0.70922361]
 [0.0374664  0.2333747 ]
 [0.98827225 0.46170792]
 [0.04472519 0.66172175]
 [0.04795199 0.49652792]
 [0.91382734 0.78239879]
 [0.60668652 0.72945275]]


In [9]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

6026.3410723821735


In [10]:
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [11]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

44.29352350802592


In [13]:
print(preds)
print("\n\n")
print(targets)

[[ 58.3616433   71.2624835 ]
 [ 80.32802961  97.32218928]
 [121.20755455 139.42416531]
 [ 24.6349028   41.90017929]
 [ 96.87066934 110.00852643]
 [ 58.1494044   70.80272028]
 [ 80.96227465  96.75786069]
 [121.46394505 140.06935433]
 [ 24.75319348  41.84823489]
 [ 96.51661025 109.90939901]
 [ 58.41282015  71.19382275]
 [ 80.10772309  97.16562114]
 [120.72474477 139.58868195]
 [ 25.23656569  41.92139056]
 [ 97.0856786  110.40534479]]



[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
