# Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                    [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                    [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("Targets :\n",targets)

Targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(f"{v}\n{r}")

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.377855  , 0.77342922],
       [0.50321538, 0.19918605],
       [0.81106496, 0.45792475]])>
<tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([ 0.21186872, -0.87524954])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[ 96.38650724  88.62131346]
 [130.78778433 116.34236637]
 [147.55788201 119.66365935]
 [ 90.40074328 103.52274706]
 [131.36708721 103.66796047]
 [ 96.38650724  88.62131346]
 [130.78778433 116.34236637]
 [147.55788201 119.66365935]
 [ 90.40074328 103.52274706]
 [131.36708721 103.66796047]
 [ 96.38650724  88.62131346]
 [130.78778433 116.34236637]
 [147.55788201 119.66365935]
 [ 90.40074328 103.52274706]
 [131.36708721 103.66796047]], shape=(15, 2), dtype=float64)


In [7]:
def mean_square_error(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mean_square_error(prediction,targets))

tf.Tensor(1582.9146193966008, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mean_square_error(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 1582.9146193966008
 
 Epoch count: 1 
 Loss value: 1165.5048030451076
 
 Epoch count: 2 
 Loss value: 883.238403694563
 
 Epoch count: 3 
 Loss value: 688.1036414457911
 
 Epoch count: 4 
 Loss value: 549.747388407435
 
 Epoch count: 5 
 Loss value: 448.9025995575377
 
 Epoch count: 6 
 Loss value: 373.2717681468577
 
 Epoch count: 7 
 Loss value: 314.94744551009666
 
 Epoch count: 8 
 Loss value: 268.79485572009725
 
 Epoch count: 9 
 Loss value: 231.43684344448837
 
 Epoch count: 10 
 Loss value: 200.61603430364733
 
 Epoch count: 11 
 Loss value: 174.79332463838924
 
 Epoch count: 12 
 Loss value: 152.89452225325326
 
 Epoch count: 13 
 Loss value: 134.14993674105844
 
 Epoch count: 14 
 Loss value: 117.99235287585887
 
 Epoch count: 15 
 Loss value: 103.99173367666222
 
 Epoch count: 16 
 Loss value: 91.81308166095967
 
 Epoch count: 17 
 Loss value: 81.18894591314688
 
 Epoch count: 18 
 Loss value: 71.90123026155948
 
 Epoch count: 19 
 Loss value: